### ISSUE TITLE
msis_matlab3D.m has issues finding compilers and getting paths right on some systems

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini-matlab#2]
Particularly on MacOS I have to hard code paths and compiler absolute location

**Comment by scivision** [comment]
https://github.com/gemini3d/gemini-matlab/blob/9d1a002711f8c2176be1d5f93f91a8b2e6f9d821/matlab/setup/msis_matlab3D.m#L37
This hardcoding of /usr/local/bin/gfortran for MacOS seems like it should work for Homebrew users, which is probably the main use case. It seems like Homebrew avoids causing a mess on user systems by avoiding making itself the default.

**Comment by scivision** [comment]
This is a general issue for build systems, including *de facto* ones as here. The universal solution is to specify via environment variable `FC` either the name or full path to the Fortran compiler.

**Comment by scivision** [comment]
this was resolved by using CMake instead of ad hoc Matlab code
